#pragma once

namespace apgame {

enum reversi_status : int {
  REVERSI_STATUS_BEFORE_GAME,
  REVERSI_STATUS_BLACK_TURN,
  REVERSI_STATUS_WHITE_TURN,
  REVERSI_STATUS_AFTER_GAME,
  REVERSI_STATUS_ERROR
};

enum reversi_command : int {
  REVERSI_COMMAND_JOIN,
  REVERSI_COMMAND_GET_GAME_STATUS,
  REVERSI_COMMAND_GET_BOARD,
  REVERSI_COMMAND_PUT_STONE,
  REVERSI_COMMAND_GET_USER_INFO,
  REVERSI_COMMAND_CLOSE
};

enum reversi_stone : char {
  EMPTY = 0,
  BLACK,
  WHITE
};

}
