#pragma once

namespace apgame {

enum ReversiStatus : int {
  REVERSI_STATUS_BEFORE_GAME,
  REVERSI_STATUS_BLACK_TURN,
  REVERSI_STATUS_WHITE_TURN,
  REVERSI_STATUS_AFTER_GAME,
  REVERSI_STATUS_ERROR
};

enum ReversiCommand : int {
  REVERSI_COMMAND_GET_COLOR,
  REVERSI_COMMAND_GET_STATUS,
  REVERSI_COMMAND_GET_BOARD,
  REVERSI_COMMAND_PUT_STONE,
  REVERSI_COMMAND_GET_LAST_STONE,
  REVERSI_COMMAND_GET_USER_INFO,
};

enum ReversiStone : char {
  REVERSI_STONE_BLACK = 1,
  REVERSI_STONE_EMPTY = 0,
  REVERSI_STONE_WHITE = -1
};

}
